!includeurl https://raw.githubusercontent.com/drogar/C4-PlantUML/master/C4_Container.puml
' uncomment the following line and comment the first to use locally
' !include C4_Container.puml

' Scope: A single container.
' Primary elements: Components within the container in scope.
' Supporting elements: Containers (within the software system in scope) plus people and software systems directly connected to the components.
' Intended audience: Software architects and developers.

' Colors
' ##################################

!global $COMPONENT_BG_COLOR="#85BBF0"

' Styling
' ##################################

skinparam rectangle<<component>> {
    StereotypeFontColor $ELEMENT_FONT_COLOR
    FontColor #000000
    BackgroundColor $COMPONENT_BG_COLOR
    BorderColor #78A8D8
}

skinparam database<<component>> {
    StereotypeFontColor $ELEMENT_FONT_COLOR
    FontColor #000000
    BackgroundColor $COMPONENT_BG_COLOR
    BorderColor #78A8D8
}

skinparam cloud<<component>> {
    StereotypeFontColor $ELEMENT_FONT_COLOR
    FontColor #000000
    BackgroundColor $COMPONENT_BG_COLOR
    BorderColor #78A8D8
}


' Elements
' ##################################

!unquoted procedure Component(e_alias, e_label, e_techn)
%set_variable_value("$component_used", "true")
rectangle "==e_label\n//<size:$TECHN_FONT_SIZE>[e_techn]</size>//" <<component>> as e_alias
!endprocedure

!unquoted procedure Component(e_alias, e_label, e_techn, e_descr)
%set_variable_value("$component_used", "true")
rectangle "==e_label\n//<size:$TECHN_FONT_SIZE>[e_techn]</size>//\n\n e_descr" <<component>> as e_alias
!endprocedure


!unquoted procedure ComponentDb(e_alias, e_label, e_techn)
%set_variable_value("$component_used", "true")
database "==e_label\n//<size:$TECHN_FONT_SIZE>[e_techn]</size>//" <<component>> as e_alias
!endprocedure

!unquoted procedure ComponentDb(e_alias, e_label, e_techn, e_descr)
%set_variable_value("$component_used", "true")
database "==e_label\n//<size:$TECHN_FONT_SIZE>[e_techn]</size>//\n\n e_descr" <<component>> as e_alias
!endprocedure


!unquoted procedure ComponentCloud(e_alias, e_label, e_techn)
%set_variable_value("$component_used", "true")
cloud "==e_label\n//<size:$TECHN_FONT_SIZE>[e_techn]</size>//" <<component>> as e_alias
!endprocedure

!unquoted procedure ComponentCloud(e_alias, e_label, e_techn, e_descr)
%set_variable_value("$component_used", "true")
cloud "==e_label\n//<size:$TECHN_FONT_SIZE>[e_techn]</size>//\n\n e_descr" <<component>> as e_alias
!endprocedure
