!includeurl https://raw.githubusercontent.com/drogar/C4-PlantUML/master/C4_Context.puml
' uncomment the following line and comment the first to use locally
' !include C4_Context.puml

' Scope: A single software system.
' Primary elements: Containers within the software system in scope.
' Supporting elements: People and software systems directly connected to the containers.
' Intended audience: Technical people inside and outside of the software development team; including software architects, developers and operations/support staff.

' Colors
' ##################################

!global $CONTAINER_BG_COLOR="#438DD5"

' Styling
' ##################################

skinparam rectangle<<container>> {
    StereotypeFontColor $ELEMENT_FONT_COLOR
    FontColor $ELEMENT_FONT_COLOR
    BackgroundColor $CONTAINER_BG_COLOR
    BorderColor #3C7FC0
}

skinparam database<<container>> {
    StereotypeFontColor $ELEMENT_FONT_COLOR
    FontColor $ELEMENT_FONT_COLOR
    BackgroundColor $CONTAINER_BG_COLOR
    BorderColor #3C7FC0
}

' Elements
' ##################################

!unquoted procedure Container(e_alias, e_label, e_techn)
%set_variable_value("$container_used", "true")
rectangle "==e_label\n//<size:$TECHN_FONT_SIZE>[e_techn]</size>//" <<container>> as e_alias
!endprocedure

!unquoted procedure Container(e_alias, e_label, e_techn, e_descr)
%set_variable_value("$container_used", "true")
rectangle "==e_label\n//<size:$TECHN_FONT_SIZE>[e_techn]</size>//\n\n e_descr" <<container>> as e_alias
!endprocedure


!unquoted procedure ContainerDb(e_alias, e_label, e_techn)
%set_variable_value("$container_used", "true")
database "==e_label\n//<size:$TECHN_FONT_SIZE>[e_techn]</size>//" <<container>> as e_alias
!endprocedure

!unquoted procedure ContainerDb(e_alias, e_label, e_techn, e_descr)
%set_variable_value("$container_used", "true")
database "==e_label\n//<size:$TECHN_FONT_SIZE>[e_techn]</size>//\n\n e_descr" <<container>> as e_alias
!endprocedure


' Boundaries
' ##################################

!unquoted procedure Container_Boundary(e_alias, e_label)
Boundary(e_alias, e_label, "Container")
!endprocedure
